language: node_js
node_js:
  - "6"
  - "5"
before_script:
  - npm install -g mocha
  - npm install -g eslint
  - npm i
script: npm test
env:
  - REACT=16
bundler_args: --retry 2
matrix:
  fast_finish: true
cache:
  directories:
    - node_modules
after_script:
    - npm run coveralls
notifications:
  webhooks: https://hook.bearychat.com/=bw9fs/travis/613010ff56ad38e540b93d5543cea6dd
  slack: ecmadao:fKFA5rnMSWRUqZrA9bS3gaD2
